### ISSUE TITLE
Перевод на русский язык (translating to Russian language)

### ISSUE THREAD

**Issue by yavasilek** [Brummolix/AutoarchiveReloaded#17]
Hey. Below is a translation into Russian.

For install.rdf

```
<em:localized>
        <Description>
            <em:locale>ru-RU</em:locale>
            <em:description>Автоматическое архивирование старых писем</em:description>
            <em:creator>Brummolix (Оригинальная версия Алексея Егорова)</em:creator>
        </Description>
    </em:localized>
```

For locale
[ru-RU.zip](https://github.com/Brummolix/AutoarchiveReloaded/files/403823/ru-RU.zip)

**Comment by Brummolix** [comment]
Thank you for the translation.
I have created a beta version with the russian language, you find it under https://github.com/Brummolix/AutoarchiveReloaded/releases/download/0.9.9.2_beta/AutoarchiveReloaded_0.9.9.2_beta.xpi

There are some things to do:
1. Contributor
I can add you as contributor. What name should I add? "yavasilek"?

2. Beta
Can you check the beta if everything with the translation is right?

3. properties text
Maybe you can shorten the text in the account property window. Otherwise a "..." is shown.
See screenshot
![account properties rus](https://cloud.githubusercontent.com/assets/6218021/17645797/1a95478c-61b0-11e6-824b-70b14bec21db.png)

4. translation for Mozilla page
Can you please translate the text under https://addons.mozilla.org/ru/thunderbird/addon/autoarchivereloaded/ (the section under "Об этом дополнении") and post it here
Please also translate the title "Automatically archives old mails (Improved version of the orginal Autoarchive Add-on)"

**Comment by yavasilek** [comment]
Hey. You can specify - yavasilek
1. I found a spelling error. Attached corrected version. [ru-RU.zip](https://github.com/Brummolix/AutoarchiveReloaded/files/418182/ru-RU.zip)
2. Cut does not work, but everything is clear.
3. OK
Thunderbird позволяет архивировать сообщения, но необходимо запускать процесс вручную для каждого сообщения.
Это дополнение позволяет автоматически архивировать сообщения по истечении определенного установленного времени.
Можно, например, использовать архивацию учетной записи IMAP (когда место на сервере ограничено) на локальный компьютер.
Инструкцию доступны по адресу http://brummolix.github.io/AutoarchiveReloaded/
Сообщить о найденных ошибках можно по адресу https://github.com/Brummolix/AutoarchiveReloaded/issues

**Пожалуйста, обратите внимание**
Используйте дополнение на свой страх и риск! Некоторые (немногие) пользователи сообщают о потери данных.

Дополнение представляет собой улучшенную версию дополнения "Autoarchive".
Улучшения:
-Архивирование не только папки Входящие, но и другие папки, такие как Отправленные (Корзина, Шаблоны, Черновики, Исходящие и Архивы, игнорируются)
-Архивирование вложенных папок
-Отдельная настройка для непрочитанных сообщений (помимо отмеченных сообщений и сообщений с меткой)
-Улучшена обработка, если сообщение отмечено или есть метка
-Добавлена активность в окне активности
-Архивирование с помощью Меню/Инструменты
-Вы можете выбрать авто архивирование при каждом запуске Thunderbird или вручную
-Добавлена (ограничено) возможность архивирования RSS аккаунтов (только с настройками по умолчанию, т.к. нет настроек архивирования RSS)
----------------------
Automatically archives old mails (Improved version of the orginal Autoarchive Add-on)"
Автоматическое архивирование старых писем (улучшенная версия оригинального дополнения Autoarchive)

**Comment by Brummolix** [comment]
Thank you.
I have included your changes and released the final version, https://github.com/Brummolix/AutoarchiveReloaded/releases/tag/0.9.9.2

It is also uploaded at Mozilla (but may take a while until it is reviewed and accepted by Mozilla)

**Comment by Brummolix** [comment]
Can you translate the following texts for the next version?

General
Logging
Save settings
Settings saved.
specific settings for account $$TITLE$$

**Comment by yavasilek** [comment]
Основные
Журналирование
Сохранить настройки
Настройки сохранены.
параметры учетной записи

**Comment by Brummolix** [comment]
Thanks
