### ISSUE TITLE
Archiving possibilities when using the Owl for Exchange add-on

### ISSUE THREAD

**Issue by laka** [Brummolix/AutoarchiveReloaded#72]
Hi,

I'm using the Owl for Exchange add-on to fetch emails... I'm guessing that limits my archiving possibilities?

Thanks,
Lasse

**Comment by Brummolix** [comment]
I have no experience with Owl.
Does it create an account like an Imap/Pop account in Thunderbird?

Does Thunderbird itself offer the archive function for a single email (try with right mouse click on an email in the list).
If this works, chances are good, that Autoarchive can also archive it.

Do you see it in the settings of Autoarchive Reloaded?
What happens if you try to archive with Autoarchive Reloaded?
Can you enable extended logging in Autoarchive Reloaded settings and then try to autoarchive?
What can you see in the logs (menu extras\developer tools\error console) then?

**Comment by laka** [comment]
Thanks for the reply!

Yeah - it creates an account in a simliar way, but I'm not sure how it works; some type of curling of the outlook.office.com? 

Anyway, the "right click -> archive" works as expected, yes.

The account is however skipped by Autoarchive Reloaded:

```
23.2.2022, 10:44:42 - AutoarchiveReloaded - INFO: check account 'TechnipFMC (Digicorner)' background.js:120:17
23.2.2022, 10:44:42 - AutoarchiveReloaded - INFO: ignore account 'TechnipFMC (Digicorner)' background.js:120:17
23.2.2022, 10:44:42 - AutoarchiveReloaded - INFO: archive (searching messages to archive) done background.js:120:17
```

**Comment by laka** [comment]
`23.2.2022, 20:58:33 - AutoarchiveReloaded - INFO: Account Info: 'TechnipFMC (Digicorner)'; type: owl; id: account3; isAccountArchivable: false`

**Comment by Brummolix** [comment]
Can you please try the beta relase of a new version of Autoarchive Reloaded to see if it works:
https://github.com/Brummolix/AutoarchiveReloaded/releases/download/1.0.0.6_beta/AutoArchiveReloaded-1.0.0.6_beta.xpi

**Comment by laka** [comment]
Seems to work great, thanks! :-)

Lasse

**Comment by Brummolix** [comment]
Release 1.0.0.6 is uploaded to addons.thunderbird.net
